### ISSUE TITLE
es delay exception

### ISSUE THREAD

**Issue by arisdu** [chaosblade-io/chaosblade-exec-jvm#302]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)

2023-03-30 09:36:35 INFO  load chaosblade module
2023-03-30 09:36:35 INFO  load create handler
2023-03-30 09:36:35 INFO  load destroy handler
2023-03-30 09:36:35 INFO  load status handler
2023-03-30 09:36:35 INFO  load chaosblade completed
2023-03-30 09:36:41 INFO  active chaosblade module
2023-03-30 09:36:41 INFO  register enhancer: RestTemplateEnhancer
2023-03-30 09:36:41 WARN  http target model has defined
2023-03-30 09:36:42 WARN  http target model has defined
2023-03-30 09:36:42 WARN  http target model has defined
2023-03-30 09:36:42 WARN  http target model has defined
2023-03-30 09:36:43 INFO  register enhancer: ServletEnhancer
2023-03-30 09:36:44 INFO  register enhancer: LogbackEnhancer
2023-03-30 09:36:44 WARN  rabbitmq target model has defined
2023-03-30 09:36:44 WARN  dubbo target model has defined
2023-03-30 09:36:44 WARN  kafka target model has defined
2023-03-30 09:36:44 INFO  register enhancer: ElasticSearchEnhancer
2023-03-30 09:36:45 INFO  command: status, request: {"headers":{},"params":{"1":"1"}}
2023-03-30 09:36:45 INFO  command: create, request: {"headers":{},"params":{"action":"delay","index":"table_index","pid":"57415","suid":"5df6b2f4de26437d","time":"30000","target":"es"}}
2023-03-30 09:36:49 ERROR elasticsearch plugin error : [Ljava.lang.String; cannot be cast to java.lang.String
java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.lang.String
        at com.alibaba.chaosblade.exec.plugin.elasticsearch.index.AbstractRequestIndex.index(AbstractRequestIndex.java:65)
        at com.alibaba.chaosblade.exec.plugin.elasticsearch.index.impl.SearchRequestIndex.getIndex0(SearchRequestIndex.java:21)
        at com.alibaba.chaosblade.exec.plugin.elasticsearch.index.AbstractRequestIndex.getIndexOfString(AbstractRequestIndex.java:26)
        at com.alibaba.chaosblade.exec.plugin.elasticsearch.ElasticSearchEnhancer.getIndex(ElasticSearchEnhancer.java:62)
        at com.alibaba.chaosblade.exec.plugin.elasticsearch.ElasticSearchEnhancer.doBeforeAdvice(ElasticSearchEnhancer.java:45)
        at com.alibaba.chaosblade.exec.common.aop.BeforeEnhancer.beforeAdvice(BeforeEnhancer.java:46)
        at com.alibaba.chaosblade.exec.bootstrap.jvmsandbox.BeforeEventListener.handleEvent(BeforeEventListener.java:76)
        at com.alibaba.chaosblade.exec.bootstrap.jvmsandbox.BeforeEventListener.onEvent(BeforeEventListener.java:49)
        at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandler.handleEvent(EventListenerHandler.java:117)
        at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandler.handleOnBefore(EventListenerHandler.java:353)
        at java.com.alibaba.jvm.sandbox.spy.Spy.spyMethodOnBefore(Spy.java:164)
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734)
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696)
        at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1092)
        at com.abchina.esdelay.service.impl.EsdelayServiceImpl.queryTable(EsdelayServiceImpl.java:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.abchina.taihang.framework.service.filter.ThreadContextCleanerFilter.doFilter(ThreadContextCleanerFilter.java:45)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
chaosblade1.6.1
elasticsearch-rest-high-level-client 6.8.9

**Comment by zzhyfeng** [comment]
This problem has been fixed in this [version.](https://github.com/chaosblade-io/chaosblade-exec-jvm/commit/99ae8831adc12f7a469c993e41369d098716d052)
You can use the latest version to do this experiment.
